### ISSUE TITLE
Front Page links to top level

### ISSUE THREAD

**Issue by domm-huma** [huma-engineering/huma-docs#53]
The aim is to have the front page that reflects the structure created for the pages relating to the product.

Currently, the front page displays the placeholders that were created initially but as work has moved on for the product knowledge base the links are no longer correct.

![image](https://user-images.githubusercontent.com/102555002/173546747-c4959353-8a5b-47a2-83e0-1d66f9af8024.png)

From the product team, we want to have a page that describes every part of the product, but we cannot update the front page as we do not control any part of the knowledge base outside of the directory "data-collection".

We would like the engineering team to update the front page to show the card for "Docs PRODUCT DOCUMENTATION":

- How it works | `/data-collection/huma-product/how-it-works`
- Modules | `/data-collection/modules/`
- ePROS / Licensed Questionnaires | `/data-collection/epros-licensed-questionnaires/`
- Features | `/data-collection/features/`

**Comment by meldee-huma** [comment]
resolved
